# docker compose for a postgres database

services:
    api:
        container_name: munch-backend
        image: ghcr.io/munch-ynov/munch-backend:main
        # build: .
        
        working_dir: /app
        restart: always
        ports:
          - 3000:3000
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - DIRECT_URL=${DIRECT_URL}
            - PORT=${PORT}
            - EXPIRATION_JWT_ACCESS_TOKEN=${EXPIRATION_JWT_ACCESS_TOKEN}
            - EXPIRATION_JWT_REFRESH_TOKEN=${EXPIRATION_JWT_REFRESH_TOKEN}
            - JWT_SECRET=${JWT_SECRET}
            - NODE_ENV=${NODE_ENV}
            - MAILGUN_KEY=${MAILGUN_KEY}
            - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
            - MAILGUN_FROM=${MAILGUN_FROM}
        env_file:
            - .env
        networks:
            - default
        volumes:
          - logs:/app/logs
networks:
  default:
    name: munch-back-network

volumes:
  logs:


